CREATE DATABASE IF NOT EXISTS my_blog;
USE my_blog;

CREATE TABLE blogs (
  id INT AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  content TEXT NOT NULL,
  category VARCHAR(255),
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);